consumer:
  kafka:
    topic: consumerinvoice
    bootstrap-servers: localhost:9092
    group-id: group_id
    auto-offset-reset: earliest
    seekToPredeterminedOffset: true
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    max-poll-records: 100
    heartbeat-interval: 10
    max-poll-interval: 1000000
    max-partition-fetch-bytes: 10485760
    session-timeout: 10000
    request-timeout: 1000
    retries: 3
    max-block: 5000
    max-in-flight: 512
    client-id: falcon-5
    enable-auto-commit: false
    acks: all
    timeout: 5000
    commitSize: 100
    sslConfig:
      sslEnabled: false
      trustStoreLocation: "/keystore/quote-kafka-truststore.jks"
      trustStorePassword: "****"
      keyStoreLocation: "/keystore/quote-kafka-keystore.jks"
      keyStorePassword: "****"
      sslKeyPassword: "****"